// Golden snapshots: every <name>.snapshot.json in golden/ is finalized, audited
// and compared with <name>.expected.json, a list of {"rule", "testID"} pairs
// (order-insensitive). The demo-app goldens are regenerated by
// `npm run golden --prefix eval` and must stay in sync with eval/defects.json.
#include <algorithm>
#include <filesystem>
#include <fstream>
#include <sstream>

#include "test.hpp"
#include "waypoint/finalize.hpp"
#include "waypoint/rules.hpp"

using namespace waypoint;
namespace fs = std::filesystem;

namespace {

std::string readFile(const fs::path& p) {
  std::ifstream in(p);
  std::stringstream ss;
  ss << in.rdbuf();
  return ss.str();
}

std::string join(std::vector<std::string> v) {
  std::sort(v.begin(), v.end());
  std::string out;
  for (const auto& s : v) out += s + "\n";
  return out;
}

}  // namespace

TEST(golden_snapshots_match_expected_findings) {
  int checked = 0;
  for (const auto& entry : fs::directory_iterator(WAYPOINT_GOLDEN_DIR)) {
    std::string file = entry.path().filename().string();
    const std::string suffix = ".snapshot.json";
    if (file.size() <= suffix.size() || file.compare(file.size() - suffix.size(), suffix.size(), suffix) != 0) {
      continue;
    }
    std::string stem = file.substr(0, file.size() - suffix.size());
    Snapshot s = snapshotFromJson(Json::parse(readFile(entry.path())));
    finalize(s);
    AuditReport r = audit(s);
    std::vector<std::string> got, want;
    for (const auto& f : r.findings) {
      std::string tid = f.data.str("testID", "#" + std::to_string(f.nodeId));
      got.push_back(f.rule + " " + tid);
    }
    Json expected = Json::parse(readFile(entry.path().parent_path() / (stem + ".expected.json")));
    for (const auto& e : expected.asArray()) want.push_back(e.str("rule") + " " + e.str("testID"));
    if (join(got) != join(want)) {
      throw wptest::Failure{"golden " + stem + " mismatch\n--- got\n" + join(got) + "--- want\n" + join(want)};
    }
    ++checked;
  }
  EXPECT_TRUE(checked >= 1);
}
